# Generated by Django 5.0.4 on 2024-08-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CrudUser",
        ),
    ]
